WorkshopPrototype:
    decorator: true
    config:
        fields:
            conference:
                type: "String!"
            name:
                type: "String!"

Workshop:
    type: object
    inherits: [WorkshopPrototype]
    config:
        fields:
            id:
                type: "UUID!"

WorkshopInput:
    type: input-object
    inherits: [WorkshopPrototype]
