Query:
    inherits:
        - WorkshopQuery
    type: object
    config:
        description: "Main Queries"
        fields:
            Hello:
                type: "String"
                resolve: "World"
            HelloFromInput:
                type: "String"
                args:
                    name:
                        type: "String!"
                resolve: "@=args['name'] ?: 'Guest'"

WorkshopQuery:
    decorator: true
    config:
        fields:
            Workshops:
                type: "[Workshop]"
                resolve: '@=resolver("app.graphql.resolver.workshop.all")'
            WorkshopsDirectly:
                type: "[Workshop]"
                resolve: '@=resolver("App\\Infrastructure\\GraphQL\\Workshop\\Resolver\\Workshop::allWorkshops")'
            WorkshopsRelay:
                type: "WorkshopConnection"
                argsBuilder: "Relay::Connection"
                resolve: '@=resolver("app.graphql.resolver.workshop.relay", [args])'
            Workshop:
                type: "Workshop"
                args:
                    id:
                        type: "UUID!"
                resolve: '@=resolver("app.graphql.resolver.workshop.by.id", [args["id"]])'
