Conference:
    type: object
    config:
        fields:
            name:
                type: "String"
            dateStart:
                type: "Date"
            dateEnd:
                type: "Date"
