Person:
    type: object
    config:
        fields:
            id:
                type: "UUID!"
            name:
                type: "String!"
            bornDate:
                type: "Date!"
            enrolledWorkshops:
                type: "[Workshop]"
                resolve: "@=resolver('app.graphql.resolver.workshop.by.people', [value])"
