Person:
    type: object
    config:
        fields:
            id:
                type: "UUID!"
            name:
                type: "String!"
            bornDate:
                type: "Date!"
                public: '@=service("App\\Infrastructure\\GraphQL\\Workshop\\Resolver\\WorkshopPeople").canViewBornDate(typeName, fieldName)'
                access: '@=service("App\\Infrastructure\\GraphQL\\Workshop\\Resolver\\WorkshopPeople").canAccessBornDate(value)'
            enrolledWorkshops:
                type: "[Workshop]"
                complexity: '@=2 + childrenComplexity'
                resolve: "@=resolver('app.graphql.resolver.workshop.by.people', [value])"
