WorkshopPrototype:
    decorator: true
    config:
        fields:
            conference:
                type: "String!"
            name:
                type: "String!"

Workshop:
    type: object
    inherits: [WorkshopPrototype]
    config:
        fields:
            id:
                type: "UUID!"
            enrolledPeople:
                type: "[Person]"
                description: "All People related to this Workshop"
                resolve: '@=resolver("app.graphql.resolver.people.by.workshop", [value, args])'

WorkshopInput:
    type: input-object
    inherits: [WorkshopPrototype]

WorkshopConnection:
    type: relay-connection
    config:
        nodeType: Workshop
